INSERT INTO roles (role_name) 
SELECT 'ROLE_VIEWER' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE role_name = 'ROLE_VIEWER');

INSERT INTO roles (role_name) 
SELECT 'ROLE_ANALYST' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE role_name = 'ROLE_ANALYST');

INSERT INTO roles (role_name) 
SELECT 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE role_name = 'ROLE_ADMIN');